export { default as SignUp } from './auth/signup/index'
export { default as SignIn } from './auth/signin/index'
export { default as ForgotPassword } from './auth/forgot-password/index'
export { default as RegisterNumber } from './auth/register-phoneNumber/index'
export { default as GetStarted } from './auth/get-started/index'
export { default as VerifyNumber } from './auth/verify-phoneNumber/index'
export { default as ProfileSetup } from './auth/profile-setup/index'