export { default as SignUp } from './signup/index'
export { default as SignIn } from './signin/index'
export { default as ForgotPassword } from './forgot-password/index'
export { default as RegisterNumber } from './register-phoneNumber/index'
export { default as GetStarted } from './get-started/index'
export { default as VerifyNumber } from './verify-phoneNumber/index'
export { default as ProfileSetup } from './profile-setup/index'